---

  # loki:
  #   image: grafana/loki:2.5.0
  #   restart: unless-stopped
  #   volumes:
  #     - ./loki-local-config.yml:/etc/loki/local-config.yml
  #   command: -config.file=/etc/loki/local-config.yml
  #   networks:
  #     - monitor
  #   ports:
  #     - "3100:3100"

- name: Copy loki config
  template:
    src: "loki-local-config.yml.j2"
    dest: "/files/loki-local-config.yaml"
  when: ansible_check_mode is not defined or not ansible_check_mode


- name: Create Loki conatiner
  community.docker.docker_container:
    name: loki
    image:  grafana/loki:2.5.0
    restart_policy: "unless-stopped"
    volumes:
      - "/files/loki-local-config.yaml:/etc/loki/local-config.yaml"
    command: --config.file=/etc/loki/local-config.yaml
    networks:
      - name: monitor
        aliases: 
          - loki
    ports:
      - "3100:3100"

  # promtail:
  #   image: grafana/promtail:2.5.0
  #   restart: unless-stopped
  #   volumes:
  #     - ./promtail-config.yml:/etc/promtail/promtail-config.yml
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --config.file=/etc/promtail/promtail-config.yml
  #   networks:
  #     - monitor
