---
- name: Install Docker
  include_role:
    name: install_docker
  tags: init

- name: Create monitor network
  docker_network:
    name: monitor

- name: Create Prometheus volume
  community.docker.docker_volume:
    name: prometheus-data

- name: Create Grafana volume
  community.docker.docker_volume:
    name: grafana-data

- name: Copy volume files
  copy:
    src: "files/"
    dest: "/files/"
  when: ansible_check_mode is not defined or not ansible_check_mode

- name: Copy Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: /files/prometheus.yml

- name: Copy alertmanager configuration file
  template:
    src: alertmanager.yml.j2
    dest: /files/alertmanager.yml

- name: Copy grafana configuration file
  template:
    src: grafana.ini.j2
    dest: /files/grafana.ini

- name: Create prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:v2.31.1
    restart_policy: "unless-stopped"
    volumes:
      - "/files/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
      - "/files/rules.yml:/etc/prometheus/rules.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=24h"
      - "--web.enable-lifecycle"
    networks:
      - name: monitor
        aliases: 
          - prometheus
    published_ports:
      - "9090:9090"

- name: Create Grafana conatiner
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:8.2.4
    restart_policy: "unless-stopped"
    volumes:
      - grafana-data:/var/lib/grafana
      - /files/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - name: monitor
        aliases: 
          - grafana
    ports:
      - "3000:3000"

- name: set up Loki and Promtail
  include_tasks: loki_set_up.yml

- name: Create Alert Manager container
  community.docker.docker_container:
    name: alertmanager
    image: prom/alertmanager:v0.23.0
    restart_policy: "unless-stopped"
    ports:
      - "9093:9093"
    volumes:
      - "/files/alertmanager.yml:/config/alertmanager.yml"
    command: --config.file=/config/alertmanager.yml
    networks:
      - name: monitor
        aliases: 
          - alertmanager

- name: Add Prometheus datasource
  community.grafana.grafana_datasource:
    name: Prometheus
    is_default: True
    url: "http://{{ groups['monitoring'][0] | default('localhost') }}:3000"
    # url: "http://{{ domain_name }}/grafana/"
    ds_type: prometheus
    ds_url: "http://prometheus:9090"
    access: proxy
  register: grafana_result

- debug:
    var: grafana_result 

- name: Add Loki as datasource
  community.grafana.grafana_datasource:
    name: Loki
    url: "http://{{ groups['monitoring'][0] | default('localhost') }}:3000"
    # url: "http://{{ domain_name }}/grafana/"
    ds_type: loki
    ds_url: "http://loki:3100"
    access: proxy
  register: grafana_result

- debug:
    var: grafana_result 

- name: Create Node dashboard
  community.grafana.grafana_dashboard:
    grafana_url: "http://{{ groups['monitoring'][0] | default('localhost') }}:3000"
    path: "/files/{{ item.name }}.json"
    overwrite: True
  loop:
    - {name: node}
    - {name: nginx}
    # - {name: prometheus}
    - {name: flask}
  ignore_errors: true



