---
apiVersion: v1
kind: Secret
metadata:
  name: microblog-secrets
type: Opaque
data:
  SECRET_KEY: bXktc2VjcmV0LWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: bXktc3VwZXItc2VjcmV0LXJvb3QtcGFzc3dvcmQ=
  DB_PASSWORD: bWljcm9wYXNzdw==