groups:
  - name: More get requests than 20
    rules:
      - alert: Between20and25
        expr: flask_http_request_total{method="GET",status="200"} > 30 and flask_http_request_total{method="GET",status="200"} < 50
        for: 10s
