# syntax=docker/dockerfile:1.4
FROM python:3.8-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

RUN apk --no-cache add make=4.4.1-r1

# COPY . .
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py Makefile .pylintrc pytest.ini boot_test.sh ./

RUN <<-EOF
    python -m venv .venv
    .venv/bin/pip3 install -r requirements/test.txt
EOF

ENV FLASK_APP microblog.py

RUN <<-EOF
    chmod +x boot_test.sh
    chown -R microblog:microblog ./
EOF

ENV prometheus_multiproc_dir /tmp

USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot_test.sh"]
