---
# -   import_playbook: gather_instances.yml
# -   import_playbook: terminate_instances.yml
# -   import_playbook: provision_instances.yml
# -   import_playbook: gather_instances.yml
# -   import_playbook: 10-first-minutes.yml
-   import_playbook: gather_instances.yml
-   import_playbook: set_up_microblog.yml
    vars:
      app_version: "{{ app_version }}"