- name: Create new user with initial user
  remote_user: "{{ old_user }}"
  import_tasks: create_new_user.yml

- name: Update config and delete old user
  remote_user: "{{ server_user }}"
  import_tasks: update_ssh_config.yml