---
-   name: Replace sshd_config
    template:
      src: sshd_config.j2
      dest: /etc/ssh/sshd_config
    notify: restart ssh

-   name: Flush handlers
    meta: flush_handlers

-   name: Remove default user
    user:
        name: "{{ old_user }}"
        state: absent
        force: yes
        remove: yes
    # ignore_errors: yes