name: Main workflow on new release

on:
  release:
    types: [published]

jobs:
  build-and-test:
    uses: ./.github/workflows/python-app.yml
  continuous-security:
    uses: ./.github/workflows/continuous-security.yml
    needs: build-and-test
  publish-to-docker-hub:
    uses: ./.github/workflows/publish-to-docker-hub.yml
    needs: continuous-security
    secrets: inherit
  continuous-delivery:
    uses: ./.github/workflows/continuous-delivery.yml
    needs: [build-and-test, continuous-security, publish-to-docker-hub]
    secrets: inherit
